before_install:
   - wget https://s3.amazonaws.com/rebar3/rebar3
   - chmod u+x ./rebar3
install: "true"
language: erlang
otp_release:
  - 26.2.3
  - 25.3.2
  - 24.3.4
script:
  - ./rebar3 do xref,eunit,dialyzer,coveralls send
